In [2]:
from google.colab import files

uploaded = files.upload()

Saving ecommerce .csv to ecommerce .csv

In [5]:
import pandas as pd
df = pd.read_csv('ecommerce .csv')
df.head(10)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Sub_Category,Product_Name,Quantity,Price,Discount,Payment_Mode,Shipping_Cost,Profit
0,1001,2025-01-27,17,Priya,North,Mumbai,Electronics,Laptop,Study Table,3,21474,0,NetBanking,409,10899.45
1,1002,2024-04-06,106,Neha,West,Bangalore,Furniture,Sofa,Story Book,2,49855,15,NetBanking,142,12549.36
2,1003,2024-07-28,124,Priya,North,Chennai,Clothing,Jacket,Story Book,5,15041,5,Card,659,12071.86
3,1004,2024-01-06,185,Ankit,West,Kolkata,Books,Study,Jeans Pant,4,3326,10,COD,193,2547.89
4,1005,2024-03-04,80,Ravi,West,Jaipur,Clothing,Tshirt,Office Chair,3,57042,20,COD,414,34213.76
5,1006,2024-06-27,98,Ravi,North,Delhi,Electronics,Mobile,iPhone,1,41184,20,UPI,459,3764.95
6,1007,2024-11-19,172,Suman,East,Chennai,Furniture,Chair,Polo Tshirt,4,59027,0,UPI,204,27405.45
7,1008,2024-04-10,115,Neha,West,Delhi,Books,Comics,iPhone,5,8685,10,Card,121,3447.81
8,1009,2024-06-21,80,Kiran,North,Jaipur,Books,Magazine,Story Book,1,57757,5,UPI,517,8444.88
9,1010,2025-05-06,29,Ravi,North,Chennai,Grocery,Rice,Wooden Bed,5,38213,0,Card,563,37358.23

In [6]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Region           0
City             0
Category         0
Sub_Category     0
Product_Name     0
Quantity         0
Price            0
Discount         0
Payment_Mode     0
Shipping_Cost    0
Profit           0
dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.shape

(450, 15)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       450 non-null    int64
 1   Order_Date     450 non-null    object
 2   Customer_ID    450 non-null    int64
 3   Customer_Name  450 non-null    object
 4   Region         450 non-null    object
 5   City           450 non-null    object
 6   Category       450 non-null    object
 7   Sub_Category   450 non-null    object
 8   Product_Name   450 non-null    object
 9   Quantity       450 non-null    int64
 10  Price          450 non-null    int64
 11  Discount       450 non-null    int64
 12  Payment_Mode   450 non-null    object
 13  Shipping_Cost  450 non-null    int64
 14  Profit         450 non-null    float64
dtypes: float64(1), int64(6), object(8)
memory usage: 52.9+ KB

In [10]:
df.describe()

,Order_ID,Customer_ID,Quantity,Price,Discount,Shipping_Cost,Profit
count,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000,450.0000
mean,1225.500000,100.762222,3.064444,35728.193333,9.766667,367.420000,16103.1032
std,130.048068,57.489179,1.383269,20847.627457,7.079016,187.625638,14250.8544
min,1001.000000,1.000000,1.000000,302.000000,0.000000,50.000000,38.2500
25%,1113.250000,52.250000,2.000000,16619.500000,5.000000,209.250000,5563.2950
50%,1225.500000,100.000000,3.000000,35768.500000,10.000000,373.000000,11307.0450
75%,1337.750000,148.000000,4.000000,53804.000000,15.000000,520.750000,22402.5775
max,1450.000000,199.000000,5.000000,69864.000000,20.000000,700.000000,79391.4700

In [12]:
df['Revenue'] = df['Quantity'] * df['Price'] * (1 - df['Discount']/100)

In [13]:

df['Order_Date'] = pd.to_datetime(df['Order_Date'])

df['Month'] = df['Order_Date'].dt.month
df['Year'] = df['Order_Date'].dt.year

In [14]:
df['Revenue'] = df['Quantity'] * df['Price'] * (1 - df['Discount']/100)
total_revenue = df['Revenue'].sum()
print("Total Revenue", total_revenue)

Total Revenue 43626334.400000006

In [15]:
df.groupby('Product_Name')['Revenue'].sum() \
    .sort_values(ascending=False) \
    .head(10)

Product_Name
Office Chair    5095235.90
iPhone          4687427.25
Samsung TV      4662448.15
Polo Tshirt     4596338.65
Wooden Bed      4493664.30
Study Table     4452521.00
Story Book      4313107.35
Rice Pack       3990602.10
Jeans Pant      3898077.90
Dell Laptop     3436911.80
Name: Revenue, dtype: float64

In [16]:
df.groupby('Region')["Revenue"].sum()

Region
East     10842155.85
North     9926539.20
South    12744702.80
West     10112936.55
Name: Revenue, dtype: float64

In [17]:
df.groupby('Month')['Revenue'].sum()

Month
1     6507495.40
2     4917619.50
3     4893024.80
4     5310741.05
5     3766967.35
6     3261832.60
7     1433221.10
8     2421569.80
9     2909164.35
10    3221442.65
11    2699329.00
12    2283926.80
Name: Revenue, dtype: float64

In [18]:
repeat = df['Customer_ID'].value_counts()
repeat_customers = repeat[repeat > 1]
len(repeat_customers)

139

In [ ]:
df.groupby('Payment_Mode')['Revenue'].sum()

Payment_Mode
COD            9848798.30
Card          11221101.75
NetBanking    11975006.35
UPI           10581428.00
Name: Revenue, dtype: float64

In [ ]:
import pandas as pd
df = pd.read_csv('ecommerce .csv')
df.groupby('Category')['Profit'].sum()

Category
Books          1560041.32
Clothing       1711886.14
Electronics    1346073.18
Furniture      1091346.61
Grocery        1537049.19
Name: Profit, dtype: float64

outlier detection

In [ ]:
df.sort_values('Price', ascending=False).head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Sub_Category,Product_Name,Quantity,Price,Discount,Payment_Mode,Shipping_Cost,Profit
400,1401,2024-09-06,81,Kiran,East,Mumbai,Electronics,TV,Rice Pack,4,69864,10,COD,345,33392.20
301,1302,2024-08-11,197,Pooja,West,Jaipur,Clothing,Jeans,Polo Tshirt,5,69789,10,UPI,286,69781.79
24,1025,2024-06-11,77,Amit,West,Pune,Books,Magazine,Office Chair,1,69656,10,COD,538,15576.66
254,1255,2024-04-24,57,Amit,North,Jaipur,Grocery,Snacks,Polo Tshirt,2,69452,5,NetBanking,289,29681.87
429,1430,2024-12-27,16,Rohit,South,Delhi,Books,Comics,Story Book,1,69380,0,NetBanking,260,6075.15

In [ ]:
df.sort_values('Quantity', ascending=False).head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Sub_Category,Product_Name,Quantity,Price,Discount,Payment_Mode,Shipping_Cost,Profit
445,1446,2024-09-26,142,Nisha,South,Kolkata,Clothing,Tshirt,iPhone,5,46041,10,COD,506,17491.18
446,1447,2025-02-07,13,Suman,North,Bangalore,Grocery,Fruits,Jeans Pant,5,2811,20,COD,503,2383.35
337,1338,2024-01-03,163,Nisha,South,Jaipur,Books,Novel,Samsung TV,5,35751,10,Card,328,25755.37
340,1341,2024-10-12,110,Priya,West,Delhi,Electronics,Mobile,Story Book,5,44750,10,NetBanking,461,24674.46
16,1017,2024-05-16,11,Nisha,South,Bangalore,Clothing,Shirt,Story Book,5,36829,0,NetBanking,631,14927.73